### PR TITLE
thumbnail ScaleType

### PR DESCRIPTION
**Pull request by BarthyB**
for layout and styling purposes.

### CODE REVIEW

**Comment by UrbanChrisy** [comment]
I've added fitcenter, center inside, and center crop along with ability to set scale type and image matrix. WIth also the ability to get the imageview itself so you can get all the usability of the imageview.  
Anything else you want to be added? And I would love you comments in how it over all functions if I could.

**Comment by BarthyB** [comment]
Thank you very much!

right now I don't have any other feature requests.
There is one thing I'm trying to understand though:

In my app, the player is always in portrait mode, unless I set it to fullscreen, then it is always in landscape mode. I've never seen it rotate. Is that normal?
Could this be a feature request?

greetings,

Barthy

**Comment by UrbanChrisy** [comment]
Cool thanks for that.

Does your device have rotation on. If so ill have a look to see whats wrong.

**Comment by BarthyB** [comment]
My device has rotation enabled. I'll open a new thread with more detailed information in the next 24 hours :)

**Comment by UrbanChrisy** [comment]
When you set it full screen would you like the toggle fullscreen button to be still shown?

**Comment by UrbanChrisy** [comment]
Removed few lines of redundant code. Should be all go now. Update to 1.0.4.

**Pull request closed without merging**
